.gitignore
src/Events/StateChanged.php
src/State.php
tests/StateChangedEventTest.php

Whenever the `transition` method is called and after a successful event mutation has occurred, the `StateChanged` event is dispatched so that users can hook into it.
The event provides the original model state, the state after performing the mutation and the related transition and model.

Add prototyped implementation for StateChanged event

---

docs/working-with-states/01-configuring-states.md

This PR adds a missing dollar sign in the `@property` annotation in the docs.

Adds missing dollar sign.

---

src/Exceptions/InvalidConfig.php

`InvalidConfig::fieldNotFound` appears to not be used.

Remove unused method

---

src/HasStates.php
src/State.php
tests/StateTest.php

I'd like to hear the communities input on this. Right now a state class does not know what model field it belongs to. This makes is that we need to pass in the state field explicitly when calling some methods. Eg:
```php
$model->stateField->transitionableStates('stateField');
```
It's kind of stupid having to pass in this field parameter. In the above case, a shorthand is provided, given that there's only one state field on the model. It's far from an elegant solution, hence this PR.
Note that at the moment, I only added the technical support for coupling state objects to the fields. I still need to refactor the existing `transitionableStates` method. This means this PR would mean a breaking change, though I think it's worth it. I would combine this PR #26 before tagging a v2. 
The …

Link the field name to the state instance

---

src/HasStates.php

When using transitions by calling the `transitionTo` method it returns the Eloquent model:
```
$payment->state->transitionTo(Paid::class);
```
Using the `transitionTo` method directly will return `null`:
```
$payment->transitionTo(Paid::class);
```
This PR fixes this so the Eloquent model will be returned in both cases.

Return Eloquent model when using transitionTo method directly

---

src/HasStates.php

Makes it easier for IDEs to detect that scopes exist for the models using the HasStates trait.

Provides phpdocs for state scopes

---

docs/querybuilder-support/01-state-scopes.md
src/HasStates.php
tests/Dummy/Payment.php
tests/ScopeTest.php

We're having some difficulties in a client's project 😉, let's say we have a `payments` table that is joined by a `orders` table. Both tables have a status field so to select the `payments` status field we need to use `payments.status`. When trying to scope this:
```php
Payments::whereState('payments.status', Paid::class);
```
We get an error, because the `payments.status` state does not exists, only the `status` state exists.
This PR add a third parameter to the scope where a column can be specified:
```php
Payments::whereState('status', Paid::class, 'payments.status');
```
Extra note:
Another solution could be to only use the last part of the state to look up the state, so for `payments.status` this would be `status`. But I'm not sure this is covering all the cases.

Add column name to scope

---

tests/Dummy/ModelWithIntState.php
tests/Dummy/Payment.php
tests/Dummy/PaymentWithAllowTransitions.php
tests/Dummy/PaymentWithDefaultStatePaid.php
tests/StateChangedEventTest.php

The `pending_at` column does not exist, a `cancelled_at` column does.
The `cancelled_at`, `failed_at` and `paid_at` attributes are not casted to a `Carbon` instance, so these are just strings.
I noticed that the `cancelled_at` column is not used in any of the tests and may be removed.

Docblock fixes.

---

tests/StateChangedEventTest.php

In this test it asserts the `StateChanged` is dispatched twice.
I've removed this double assertion.

Removes double Event::assertDispatched

---

tests/StateTest.php

This test asserts that the `state` attribute is an instance of the `Paid` class.
By obtaining a fresh instance of the `Payment` model you can be sure that the `state` attribute is properly unserialized when it is retrieved from the database.

Obtain fresh payment instance.

---

composer.json

I don't think there is a need to include the `barryvdh/laravel-ide-helper` package as a dev requirement, so I have removed it.

Remove laravel-ide-helper

---

composer.json

`larapack/dd` just provides helper methods, they already exist in the `symfony/var-dumper` package.
Removed `larapack/dd` in favor of `symfony/var-dumper`.

Replace larapack/dd

---

tests/Dummy/Payment.php
tests/Dummy/PaymentWithAllowTransitions.php
tests/Dummy/PaymentWithDefaultStatePaid.php
tests/TestCase.php

The `cancelled_at` column is not used in any of the tests, so I removed it.

Remove unused cancelled_at column.

---

src/State.php

The `resolveStateMapping` method is declared private, so calling it with `self` instead of `static`.

Change static to self

---

src/State.php
tests/Dummy/IntStates/IntStateB.php
tests/ScopeTest.php

I had two states, let's say `Draft` and `Published` with values of `0` and `1`:
```php
class Draft extends PostState
{
public static $name = 0;
}
// and
class Published extends PostState
{
public static $name = 1;
}
```
Now when you scope the model like so:
```php
Post::whereState('state', Draft::class)
```
This will return the published ones instead of the expected posts with state `Draft`.
This is because of the `$name` property in the `Draft` state is set to `0`.
In this scenario the state class is not resolved properly in the `resolveStateClass` method.
This PR aims to solve this issue.
Added a test as well.

Fix scope with state zero

---

src/HasStates.php
tests/Dummy/PaymentWithMultipleStates.php
tests/TestCase.php
tests/TransitionToTest.php

I ran into a scenario where I wanted to check if a **currently applied state** can transition to another given state. Instead of trying the transition using `transition()` or `transitionTo()` and catching any exception I added a new `canTransitionTo($to, ?string $field = null)` method.
```php
use Spatie\ModelStates\Tests\Dummy\Payment;
use Spatie\ModelStates\Tests\Dummy\States\Created;
use Spatie\ModelStates\Tests\Dummy\States\Paid;
use Spatie\ModelStates\Tests\Dummy\States\Pending;
$payment = Payment::create([
'state' => Created::class,
]);
$payment->canTransitionTo(Pending::class); // true
$payment->canTransitionTo('pending');      // true
$payment->canTransitionTo(Paid::class);    // false
$payment->canTransitionTo('paid');         // false
```

Add HasStates transition check method

---

.gitignore
src/Exceptions/TransitionNotFound.php

To make easily get current update when reach exception handler
```php
// App\Exceptions\Handler
public function render($request, Throwable $exception)
{
if ($request->expectsJson() && $exception instanceof TransitionNotFound) {
$from = $exception->getFrom();
$to = $exception->getTo();
$model = $exception->getModelClass();
$from = (new $from(new $model()))::$name;
$to = (new $to(new $model()))::$name;
$exception = new HttpException(
Response::HTTP_UNPROCESSABLE_ENTITY,
"Invalid transition from $from to $to.",
$exception
);
}
return parent::render($request, $exception);
}
```
will result:
```
{
"message": "Invalid transition from in-queue to in-queue.",
```
state class:
```php
<?php
namespace App\States\Orders;
class OrderInQueueState extends BaseOrderState
{
public static $name = …
```

Set getter attribute in TransitionNotFound

---

.github/workflows/run-tests.yml
composer.json

Minimum PHP version for Laravel 8 will be 7.3, so we don't need to test against PHP 7.2.
Added an `exclude` to the matrix in `run-tests.yml` but I am not sure if I did this correctly.

Support Laravel 8

---

CHANGELOG.md

@brendt Can you release a `1.9` version to support Laravel 8?
Thanks

Release 1.9 to support Laravel 8

---

src/State.php
tests/TransitionTest.php

laravel-model-states give the following error when one attempts to make two consecutive transitions:
~~~
Error: Typed property Spatie\ModelStates\State::$field must not be accessed before initialization
~~~
The problem is that when a new state is created by transition(), the $field property is not set. Therefore, the first transition is ok (because $field is set when the model is retrieved), but the second fails.
The pull request contains a possible solution and a test for the issue.

Fix bug on two consecutive transitions

---

README.md
composer.json
config/model-states.php
docs/04-installation-setup.md
src/ModelStatesServiceProvider.php
src/State.php
tests/Dummy/TestModel.php
tests/Dummy/TestModelUpdatingEvent.php
tests/Dummy/Transitions/CustomDefaultTransition.php
tests/StateTest.php

This pull request adds a config file (using your `spatie/laravel-package-tools` package) with a `default_transition` variable used to define (thus eventually override) the default transition class being used by the package.
This could be helpful in many cases: for example, my project has a model subscriber who listens to the `updating` event, but I don't want it to be fired when updating the model state. This can be solved by saving **quietly** the model changes: here's the reason why I'd need to customize the DefaultTransition class!
I updated the README and also the docs file, hope I didn't miss anything!

ADD default transition config value

---

src/State.php
tests/Dummy/Transitions/CustomTransition.php
tests/StateTest.php
tests/TransitionTest.php

Hi, I find it annoying that a transition can fail even though canTransitionTo returns true, so I have updated canTransitionTo to include a check for that.
NOTE this PR has no tests yet, but I'm happy to commit that time if you are interested in this PR.

When checking if a transition is allowed, also check the custom Transition

---

docs/working-with-states/03-listing-states.md

I think the namespace for the `HasStates` should be the from the spatie-package right? Hope I spotted that correctly.

Update 03-listing-stated.md // Wrong namespace in the docs

---

docs/querybuilder-support/01-state-scopes.md
src/HasStates.php
tests/Dummy/QueryBuilderTest.php

Hi. 
PR introduces `orWhereState` and `orWhereNotState` methods.

Add orWhereState and orWhereNotState

---

docs/working-with-states/01-configuring-states.md
src/State.php
src/StateConfig.php
tests/Dummy/ModelStates/AnotherDirectory/StateF.php
tests/Dummy/ModelStates/AnotherDirectory/StateG.php
tests/Dummy/ModelStates/AnotherDirectory/StateH.php
tests/Dummy/ModelStates/ModelState.php
tests/StateCastingTest.php
tests/StateTest.php

Added a `registerState($stateClass)` method on the `StateConfig` class to be able to include concrete state implementations other than the ones in the same directory as the abstract base class.
Implementing the functionality asked in [this discussion](https://github.com/spatie/laravel-model-states/discussions/202).
Also added what I considered relevant tests, and a subsection with the new functionality in the docs.

Manually register concrete state classes

---

src/StateCaster.php
tests/StateCastingTest.php

When changing state the "Field" property is not always set
eg.
```php
$model->state = new StageB($model);
$model->state->getField() // Throws Error: Typed property Spatie\ModelStates\State::$field must not be accessed before initialization
```
This can cause errors if you perform an action such as `$model->state->transitionableStates()` straight after setting the value.
This fixes that but always setting the "Field" property in the "set" part of the caster

Ensures field is always set when changing states

---

src/DefaultTransition.php
src/Events/StateChanged.php
src/Exceptions/CouldNotPerformTransition.php
src/Exceptions/InvalidConfig.php
src/HasStates.php
src/State.php
tests/Dummy/Transitions/CustomDefaultTransition.php

Hello.
I have have been using this library in my project and it's great!
In my project i'm also working with classes wich act like Eloquent's models but aren't strictly that type (due to the complexity of satisfying the Model class).
This library works great also in this situation but i've had to remove the PHP strict type defininitions.
Interestingly this is also how Laravel defines the CastInboundInterface, by using PHPdoc instead of strict types.
I assume it must be done for this reason?
```PHP
//from Illuminate\Contracts\Database\Eloquent\CastsInboundAttributes
interface CastsInboundAttributes
{
/**
* Transform the attribute to its underlying model values.
*
* @param  \Illuminate\Database\Eloquent\Model  $model
* @param  string  $key
* @param  mixed  $value
* @param  array …
```

Removed Model type enforcement and replaced with PHPDoc

---

docs/working-with-states/02-serializing-states.md

Hypens conflict with finding the transitionable states as they are used in the allowed transitions keys in the StateConfig class, they look something like 'fromState-toState', and this string is exploded at the hypen. If you have a hypen in the name, like "from-state-to-state" we confuse the system as the hyphen wont divide the class into valid states. (view StateConfig class, line 89).

Recommend not to use hypens in the name

---

docs/working-with-states/01-configuring-states.md
src/Attributes/AttributeLoader.php
src/Attributes/RegisterState.php
tests/AttributeStateTest.php
tests/Dummy/AttributeState/AnotherDirectory/AttributeStateC.php
tests/Dummy/AttributeState/AnotherDirectory/AttributeStateD.php
tests/Dummy/AttributeState/AnotherDirectory/AttributeStateE.php
tests/Dummy/AttributeState/AnotherDirectory/AttributeStateF.php
tests/Dummy/AttributeState/AttributeState.php

This PR adds a missing attribute called `RegisterState`, in addition to the `AllowTransition` and `DefaultState` attribute. Before, it was only possible to register states using the `->registerState()` in the config, whilst the transition and default state configs had their own attribute.
With this PR, people can now completely configure their states using attributes.
Thanks!

Add missing `RegisterState` Attribute

---

docs/working-with-states/01-configuring-states.md
src/State.php
src/StateConfig.php
tests/Dummy/CustomEventModelState/CustomEventModelState.php
tests/Dummy/CustomEventModelState/CustomEventModelStateA.php
tests/Dummy/CustomEventModelState/CustomEventModelStateB.php
tests/Dummy/CustomEventModelState/CustomInvalidEventModelState.php
tests/Dummy/CustomEventModelState/CustomInvalidEventModelStateA.php
tests/Dummy/CustomEventModelState/CustomInvalidEventModelStateB.php
tests/Dummy/CustomEventModelState/CustomInvalidStateChangedEvent.php
tests/Dummy/CustomEventModelState/CustomStateChangedEvent.php
tests/Dummy/TestModelCustomEvent.php
tests/Dummy/TestModelCustomInvalidEvent.php
tests/StateTest.php

This PR add the functionality of registering a custom `StateChanged` event. I stumbled upon this myself on a project for a client, where I wanted to listen to a specific state change and apply logic for this specific state. 
Since only the `StateChanged` event is fired, I have to add all the listeners to this event and then place if statements to check if the model is equal to the model I want the logic to apply to.
**Example**
In the event service provider I register `StateXChangedListener` to the `StateChanged` event. Right now I have to do this in the listener:
```php
if ($event->model::class === ModelWithStateX::class) {
// Apply logic for StateX state change
}
```
Another way is to use the `updating` event on the model. But this is also not ideal as I don't know which state …

Feature/Allow to set custom StateChanged event

---

docs/working-with-states/01-configuring-states.md

- A line break is missing in `use` statements
- An invalid `use const` is present

Typo in 01-configuring-states.md

---

src/State.php

This PR adds generics PHPDoc annotations to the State class.
Allows for using in a class that extends State a PHPDoc like:
```
/**
* @extends \Spatie\ModelStates\State<\App\Models\MyModel>
*/
```
in order for tools like PHPStan to understand that, e.g., `getModel()` will return an instance of `MyModel`.

Generics PHPDoc annotations for State class

---

src/StateCaster.php
tests/Dummy/ModelStates/StateB.php
tests/StateCastingTest.php

#251 introduced an issue where if someone has overridden `jsonSerialize` in their state classes, it would become ignored when serializing models to JSON.
This solves the issue by instead using `jsonSerialize` in the `StateCaster`.

Use jsonSerialize in StateCaster

---

src/Exceptions/CouldNotPerformTransition.php

Previously the Transition typehint in the phpdoc was not fully qualified and so IDE's and static analysers complained that the function expects a Class of type \Spatie\ModelStates\Exception\Transition

Fix missing namespace in phpdoc

---

src/StateConfig.php

All `$allowedTransitions` strings must be a class string which extends the abstract `Transition` class.

fix(config): var annotation for `$allowedTransitions`

---

composer.json
docs/working-with-transitions/01-configuring-transitions.md
src/StateConfig.php
tests/Dummy/AllowAllTransitionsState/AllowAllTransitionsState.php
tests/Dummy/AllowAllTransitionsStateWithExplicitlyRegisteredStates/AllowAllTransitionsStateWithExplicitlyRegisteredStates.php
tests/Dummy/AllowAllTransitionsStateWithNoRegisteredStates/AllowAllTransitionsStateWithNoRegisteredStates.php
tests/Dummy/AllowAllTransitionsStateWithNoRegisteredStates/StateAWithNoRegisteredStates.php
tests/Dummy/AllowAllTransitionsStateWithNoRegisteredStates/StateBWithNoRegisteredStates.php
tests/Dummy/AllowAllTransitionsStateWithNoRegisteredStates/StateCWithNoRegisteredStates.php
tests/Dummy/TestModelAllowAllTransitionsWithExplicitlyRegisteredStates.php
tests/StateTest.php

One of the great things about this package is that it will automatically load states that are placed in the same directory as the abstract base state class. There is no need to manually register concrete states in the same directory...with one exception - the `allowAllTransitions()` config method.
Currently the docs show the following example:
```php
abstract class PaymentState extends State
{
// …
public static function config(): StateConfig
{
return parent::config()
->allowAllTransitions();
}
}
```
However, this code is not possible to execute without it throwing a Spatie\ModelStates\Exceptions\InvalidConfig exception.
My pull request updates the `allowAllTransitions()` method  to automatically register the concrete state classes in the same directory as the abstract base state class, …

Make using allowAllTransitions() less cumbersome

---

docs/working-with-transitions/06-custom-default-transition-class.md
src/State.php
tests/Dummy/Transitions/CustomDefaultTransitionWithAttributes.php
tests/StateTest.php

Custom Transition can be initialized with arguments from transitionTo parameters. 
Custom **default** Transition can be registeren in the configuration for transitions between all states, but can not be initialized with arguments as **non default** transition.
When calling `transitionTo` method I would like to pass additional arguments that can be used in StateChanged event listener.
Add `...transitionArgs` to `$defaultTransition(...)` constructor call.
We need to handle status change in event listener, but depending on where `transitionTo` called from, in some cases we should notify user about event, but in some cases not. We can create custom DefaultTransition with additional silent parameter.
``` php
// CustomDefaultTransitionWithAttributes.php
class …
```

Feature: Added ...transitionArgs to default transition constructor call to allow arguments use for custom default transition

---

docs/working-with-transitions/01-configuring-transitions.md
src/Attributes/AttributeLoader.php
src/Attributes/IgnoreSameState.php
src/StateConfig.php
tests/Dummy/IgnoreSameStateModelState/IgnoreSameStateModelAttributeState.php
tests/Dummy/IgnoreSameStateModelState/IgnoreSameStateModelAttributeStateA.php
tests/Dummy/IgnoreSameStateModelState/IgnoreSameStateModelAttributeStateB.php
tests/Dummy/IgnoreSameStateModelState/IgnoreSameStateModelState.php
tests/Dummy/IgnoreSameStateModelState/IgnoreSameStateModelStateA.php
tests/Dummy/IgnoreSameStateModelState/IgnoreSameStateModelStateB.php
tests/Dummy/TestModelIgnoresSameState.php
tests/Dummy/TestModelIgnoresSameStateByAttribute.php
tests/TransitionTest.php

This adds a test for the case where transitioning to the same state fails when ignoreSameState() is not configured. This addresses the feedback in PR #267 @freekmurze

Added test to ensure same-state transition fails when not allowed

---

docs/working-with-states/01-configuring-states.md
src/HasStatesContract.php

Models using the `HasStates` trait currently can't be effectively Type Hinted when attempting to hook into external libraries.
This provided interface `HasStatesContract` will allow for type hinting of models that use States, as well as enforcement of the State functions.
This is something I ran into when building some integration with Filament, where you may have a custom re-usable Action / Form field that may not be tied to a specific model but is used for models with States.

Contract / Interface for Models that use `HasStates` trait.

---

src/StateConfig.php

Both `$baseStateClass` and `$defaultStateClass` strings must be a class string which extends the abstract `State` class or `null`.

fix(config): var annotation for `$baseStateClass` and `$defaultStateClass`

---

docs/working-with-states/01-configuring-states.md
src/StateConfig.php
tests/Dummy/RegisterStatesFromCustomDirectories/DefaultState.php
tests/Dummy/RegisterStatesFromCustomDirectories/Directory1/StateA.php
tests/Dummy/RegisterStatesFromCustomDirectories/Directory1/StateB.php
tests/Dummy/RegisterStatesFromCustomDirectories/Directory1/StateC.php
tests/Dummy/RegisterStatesFromCustomDirectories/Directory2/StateF.php
tests/Dummy/RegisterStatesFromCustomDirectories/Directory2/StateG.php
tests/Dummy/RegisterStatesFromCustomDirectories/Directory2/StateH.php
tests/Dummy/RegisterStatesFromCustomDirectories/RegisterStatesFromCustomDirectories.php
tests/Dummy/TestModelWithCustomDirectories.php
tests/RegisterStatesFromCustomDirectoriesTest.php

- Added a `registerStatesFromDirectory(string ...$directories)` method to `StateConfig `to allow registering  all state classes from one or more directories.
- Updated the documentation to include usage instructions and an example for the new method.
This change makes it easier to organize and register state classes across multiple folders, reducing boilerplate and improving maintainability for larger codebases.
Please let me know if additional or updated tests are needed

Add support for registering states from  multiple custom  directories.

---

docs/working-with-transitions/04-retrieving-transitionable-states.md
src/State.php
tests/StateTest.php

This PR adds a new transitionableStateInstances() method that returns an array of instantiated state objects instead of just their string representations. This makes it easier to access state methods directly in views or controllers without having to manually instantiate state objects.
Example use case:
```
@foreach($payment->state->transitionableStateInstances() as $stateInstance)
<div>
<span style="color: {{ $stateInstance->color() }}">{{ $stateInstance->label() }}</span>
</div>
@endforeach
```
Added tests and updated documentation to reflect this new feature.

Add `transitionableStateInstances()`  method to get state objects for all transitionable states
